server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/registration
    username: postgres
    password: **********
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

# =============================================
# SERVER CONFIGURATION
# =============================================
# server:
#   error:
#     # Always show detailed error messages in responses (helpful for debugging)
#     include-message: always
#
#     # Always show data binding errors (e.g., when form validation fails)
#     include-binding-errors: always
#
# =============================================
# SPRING FRAMEWORK CONFIGURATION
# =============================================
# spring:
#   # Database connection settings
#   datasource:
#     # Database password (should be set in a secure way)
#     password:
#
#     # JDBC connection URL for PostgreSQL database
#     # - Connects to PostgreSQL on local machine (localhost)
#     # - Uses port 5432 (default PostgreSQL port)
#     # - Database name is 'registration'
#     url: jdbc:postgresql://localhost:5432/registration
#
#     # Database lastName (should be set in a secure way)
#     lastName: registration
#
#   # JPA (Java Persistence API) configuration
#   jpa:
#     # Hibernate specific settings
#     hibernate:
#       # Database schema management strategy:
#       # 'create-drop' = create tables on startup, drop them on shutdown
#       # WARNING: Only for development! Use 'update' or 'none' in production
#       ddl-auto: create-drop
#
#     # Additional Hibernate properties
#     properties:
#       hibernate:
#         # SQL dialect for PostgreSQL (tells Hibernate how to generate SQL)
#         dialect: org.hibernate.dialect.PostgreSQLDialect
#
#         # Format SQL queries in logs for better readability
#         format_sql: true
#
#     # Show all SQL statements in console log (helpful for debugging)
#     show-sql: true
